<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PreserveCompilationContext>true</PreserveCompilationContext>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Settings.Configuration" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\DemoApi.Application\DemoApi.Application.csproj" />
		<ProjectReference Include="..\DemoApi.Domain\DemoApi.Domain.csproj" />
		<ProjectReference Include="..\DemoApi.Infra.CrossCutting\DemoApi.Infra.CrossCutting.csproj" />
		<ProjectReference Include="..\DemoApi.Infra\DemoApi.Infra.Data.csproj" />
	</ItemGroup>

</Project>