<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="TestResults\**" />
		<EmbeddedResource Remove="TestResults\**" />
		<None Remove="TestResults\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Moq" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\DemoApi.Application\DemoApi.Application.csproj" />
		<ProjectReference Include="..\..\src\DemoApi.Domain\DemoApi.Domain.csproj" />
		<ProjectReference Include="..\..\src\DemoApi.Infra\DemoApi.Infra.Data.csproj" />
		<ProjectReference Include="..\DemoApi.Tests.Builders\DemoApi.Tests.Builders.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>
</Project>